### ISSUE TITLE
HuskyUtils.escape_markdown doesn't escape mention strings

### ISSUE THREAD

**Issue by Catbuttes** [KazWolfe/HuskyBot#7]
If I change my username to the format `<@{user_id_here}>` I can get huskey to mention people

**Comment by Catbuttes** [comment]
![image](https://user-images.githubusercontent.com/39886661/76662197-38fe7280-6575-11ea-9a38-9b2fa76d80e4.png)

**Comment by KazWolfe** [comment]
Fixed with most recent commit - a few places may still use unprotected methods, but most _should_ be okay. I can't think of anything that will generate an errant mention, though.
